version: '3'
services:
  redis:
    image: redis
    ports:
      - '3004:6379'

  postgres:
    image: postgres
    ports:
      - '3005:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
